### ISSUE TITLE
serializeToString exception with xmldom@0.1.20

### ISSUE THREAD

**Issue by awerlang** [open-xml-templating/docxtemplater-image-module#38]
Yesterday I wasted a couple hours trying to make images work.

If anyone comes here with the same problem, even though the problem isn't with docxtemplater itself, I found this issue opened a couple days ago:

jindw/xmldom#146

I'd recommend specifying the exact working version of xmldom (0.1.19), or, for users of this package, using `npm shrinkwrap`. The shrinkwrap would be the safest bet anyways.

**Comment by edi9999** [comment]
I see that the problem has been fixed now with the release of a new version of xmldom.

I'm not sure if I really want to lock all dependencies, because indeed, that's what you normally do with npm shrink wrap.

It would be great if we created a shrink wrap file for this project and that it would be published into npm, and then when you install the project the dependencies are read from the shrink wrap file instead of from the package.json

**Comment by edi9999** [comment]
Do you maybe know if that is possible ?

**Comment by awerlang** [comment]
There's a topic about that in npm docs. https://docs.npmjs.com/cli/shrinkwrap#using-shrinkwrapped-packages

In short, it just works as usual.

**Comment by edi9999** [comment]
I've tested it and it doesn't seem to behave that way.

Indeed, in the npm shrinkwrap doc :

> If shrinkwrapped package A depends on shrinkwrapped package B, B's shrinkwrap will not be used as part of the installation of A

So the best possibility would be to lock down dependencies in the package.json

**Comment by edi9999** [comment]
I've set the dependency of xmldom to 0.1.21 (exact match)

https://github.com/open-xml-templating/docxtemplater-image-module/commit/be262a7c36ab2af2223b19c364015133b6c57dee#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R30
