### ISSUE TITLE
Using Picture Content Control

### ISSUE THREAD

**Issue by danrzeppa** [open-xml-templating/docxtemplater-image-module#40]
It would be cool if it was possible to use Word's Picture Content Control (under the Developer menu in Word 2016) as a placeholder for a picture that could then be replaced by the templating engine. One could set the Tag of the image to fieldName that should be used to replace the picture.

This would allow the position and size of the image to be specified in the template and no special code would need to be written.

I've taken a quick look at the code, but it's not exactly clear to me what would have to happen for this to work (if it's possible at all).

[Here is a sample docx file with a Picture Content Control](https://github.com/open-xml-templating/docxtemplater-image-module/files/91188/placeholder.docx)

**Comment by edi9999** [comment]
Hi,

that's a bit the same as the qrcode functionality that  is included in this module (eg replace images that have a qrcode in them with an image generated by the corresponding data).

However, I wish to deprecate that because one module should do one thing in my opinon.


For your information, we loop over all images in the replaceQr method : https://github.com/open-xml-templating/docxtemplater-image-module/blob/master/coffee/index.coffee#L74

More specifically the findImages().replaceImages() part.
