### ISSUE TITLE
Load images over HTTP

### ISSUE THREAD

**Issue by jsalonen** [open-xml-templating/docxtemplater-image-module#6]
Is it possible to add support for images from http sources? E.g.

    docx=new DocxGen()
        .attachModule(imageModule)
        .load(content)
        .setData({image:'http://example.com/examples/image.png'})
        .render()

**Comment by edi9999** [comment]
The problem is that the imageModule works synchronously for now. If you want, you could create a pullrequest to add async support:

I'm already doing this for the qrcode support: https://github.com/open-xml-templating/docxtemplater-image-module/blob/master/coffee/index.coffee#L73-L74

You would have to write: 	

```
if @getImageFromDataAsync?
  @getImageFromDataAsync(result,cb)
```

There is also this related issue that finds a solution to your problem (altough not a very clean one):

https://github.com/open-xml-templating/docxtemplater-image-module/issues/5

**Comment by edi9999** [comment]
Closing as stale
